graph TD
    Node_mps1uX8T5PpobUmjtMyG-39 --> Node_mps1uX8T5PpobUmjtMyG-214
    Node_mps1uX8T5PpobUmjtMyG-39 --> Node_mps1uX8T5PpobUmjtMyG-106
    Node_mps1uX8T5PpobUmjtMyG-39 --> Node_mps1uX8T5PpobUmjtMyG-99
    Node_mps1uX8T5PpobUmjtMyG-214 --> Node_mps1uX8T5PpobUmjtMyG-226
    Node_mps1uX8T5PpobUmjtMyG-179 --> Node_mps1uX8T5PpobUmjtMyG-183
    Node_mps1uX8T5PpobUmjtMyG-232 --> Node_mps1uX8T5PpobUmjtMyG-99
    Node_mps1uX8T5PpobUmjtMyG-220 --> Node_mps1uX8T5PpobUmjtMyG-93
    Node_mps1uX8T5PpobUmjtMyG-226 --> Node_mps1uX8T5PpobUmjtMyG-106
    Node_mps1uX8T5PpobUmjtMyG-226 --> Node_mps1uX8T5PpobUmjtMyG-39
    Node_mps1uX8T5PpobUmjtMyG-106 --> Node_mps1uX8T5PpobUmjtMyG-214
    Node_mps1uX8T5PpobUmjtMyG-366 --> Node_mps1uX8T5PpobUmjtMyG-366
    Node_mps1uX8T5PpobUmjtMyG-366 --> Node_mps1uX8T5PpobUmjtMyG-366
    Node_mps1uX8T5PpobUmjtMyG-366 --> Node_mps1uX8T5PpobUmjtMyG-366
    Node_mps1uX8T5PpobUmjtMyG-366 --> Node_mps1uX8T5PpobUmjtMyG-366
    Node_mps1uX8T5PpobUmjtMyG-410 --> Node_mps1uX8T5PpobUmjtMyG-112
    Node_mps1uX8T5PpobUmjtMyG-473 --> Node_mps1uX8T5PpobUmjtMyG-492
    Node_mps1uX8T5PpobUmjtMyG-410 --> Node_mps1uX8T5PpobUmjtMyG-473
    Node_mps1uX8T5PpobUmjtMyG-337 --> SFT
    Node_mps1uX8T5PpobUmjtMyG-339 --> SFT
    Node_mps1uX8T5PpobUmjtMyG-337 --> SFT
    Node_mps1uX8T5PpobUmjtMyG-337 --> Node_mps1uX8T5PpobUmjtMyG-112
    Node_mps1uX8T5PpobUmjtMyG-337 --> Node_mps1uX8T5PpobUmjtMyG-492
    Node_mps1uX8T5PpobUmjtMyG-340 --> SFT
    Node_mps1uX8T5PpobUmjtMyG-340 --> Node_mps1uX8T5PpobUmjtMyG-492
    Node_mps1uX8T5PpobUmjtMyG-112 --> Node_mps1uX8T5PpobUmjtMyG-492