graph TD
    Node_mps1uX8T5PpobUmjtMyG_1["Node_mps1uX8T5PpobUmjtMyG-1"]
    Node_mps1uX8T5PpobUmjtMyG_2["Node_mps1uX8T5PpobUmjtMyG-2"]
    Node_mps1uX8T5PpobUmjtMyG_3["Node_mps1uX8T5PpobUmjtMyG-3"]
    Node_mps1uX8T5PpobUmjtMyG_4["Node_mps1uX8T5PpobUmjtMyG-4"]
    Node_mps1uX8T5PpobUmjtMyG_5["Node_mps1uX8T5PpobUmjtMyG-5"]
    Node_mps1uX8T5PpobUmjtMyG_6["Node_mps1uX8T5PpobUmjtMyG-6"]
    Node_mps1uX8T5PpobUmjtMyG_38["Node_mps1uX8T5PpobUmjtMyG-38"]
    Node_mps1uX8T5PpobUmjtMyG_39["Node_mps1uX8T5PpobUmjtMyG-39"]
    Node_mps1uX8T5PpobUmjtMyG_42["Node_mps1uX8T5PpobUmjtMyG-42"]
    Kubernetes["Kubernetes"]
    Node_mps1uX8T5PpobUmjtMyG_92["Node_mps1uX8T5PpobUmjtMyG-92"]
    Node_mps1uX8T5PpobUmjtMyG_93["Node_mps1uX8T5PpobUmjtMyG-93"]
    Node_mps1uX8T5PpobUmjtMyG_98["Node_mps1uX8T5PpobUmjtMyG-98"]
    Node_mps1uX8T5PpobUmjtMyG_99["Node_mps1uX8T5PpobUmjtMyG-99"]
    Node_mps1uX8T5PpobUmjtMyG_105["Node_mps1uX8T5PpobUmjtMyG-105"]
    Node_mps1uX8T5PpobUmjtMyG_106["Node_mps1uX8T5PpobUmjtMyG-106"]
    Node_mps1uX8T5PpobUmjtMyG_173["Node_mps1uX8T5PpobUmjtMyG-173"]
    Node_mps1uX8T5PpobUmjtMyG_174["Node_mps1uX8T5PpobUmjtMyG-174"]
    Node_mps1uX8T5PpobUmjtMyG_175["Node_mps1uX8T5PpobUmjtMyG-175"]
    Node_mps1uX8T5PpobUmjtMyG_176["Node_mps1uX8T5PpobUmjtMyG-176"]
    Node_mps1uX8T5PpobUmjtMyG_177["Node_mps1uX8T5PpobUmjtMyG-177"]
    Node_mps1uX8T5PpobUmjtMyG_178["Node_mps1uX8T5PpobUmjtMyG-178"]
    Node_mps1uX8T5PpobUmjtMyG_179["Node_mps1uX8T5PpobUmjtMyG-179"]
    Node_mps1uX8T5PpobUmjtMyG_180["Node_mps1uX8T5PpobUmjtMyG-180"]
    Node_mps1uX8T5PpobUmjtMyG_183["Node_mps1uX8T5PpobUmjtMyG-183"]
    TCP_31773["TCP 31773"]
    TCP_6443TCP_2379___2380TCP_10250/10251/10252/10255TCP_3000_32767TCP_6379["TCP 6443TCP 2379 - 2380TCP 10250/10251/10252/10255TCP 3000-32767TCP 6379"]
    TCP_9200["TCP 9200"]
    TCP_9100["TCP 9100"]
    TCP_9042_/_9160["TCP 9042 / 9160"]
    Node_mps1uX8T5PpobUmjtMyG_199["Node_mps1uX8T5PpobUmjtMyG-199"]
    AdminHost["AdminHost"]
    TCP_6379["TCP 6379"]
    MinIO["MinIO"]
    ElasticSearch["ElasticSearch"]
    Cassandra["Cassandra"]
    Load_Balancer_/_Reverse_Proxy["Load Balancer / Reverse Proxy"]
    Node_mps1uX8T5PpobUmjtMyG_210["Node_mps1uX8T5PpobUmjtMyG-210"]
    WIRE["WIRE"]
    Server_1["Server 1"]
    Node_mps1uX8T5PpobUmjtMyG_213["Node_mps1uX8T5PpobUmjtMyG-213"]
    Node_mps1uX8T5PpobUmjtMyG_214["Node_mps1uX8T5PpobUmjtMyG-214"]
    Node_mps1uX8T5PpobUmjtMyG_217["Node_mps1uX8T5PpobUmjtMyG-217"]
    Kubernetes["Kubernetes"]
    Node_mps1uX8T5PpobUmjtMyG_219["Node_mps1uX8T5PpobUmjtMyG-219"]
    Node_mps1uX8T5PpobUmjtMyG_220["Node_mps1uX8T5PpobUmjtMyG-220"]
    Node_mps1uX8T5PpobUmjtMyG_225["Node_mps1uX8T5PpobUmjtMyG-225"]
    Node_mps1uX8T5PpobUmjtMyG_226["Node_mps1uX8T5PpobUmjtMyG-226"]
    Node_mps1uX8T5PpobUmjtMyG_231["Node_mps1uX8T5PpobUmjtMyG-231"]
    Node_mps1uX8T5PpobUmjtMyG_232["Node_mps1uX8T5PpobUmjtMyG-232"]
    Node_mps1uX8T5PpobUmjtMyG_243["Node_mps1uX8T5PpobUmjtMyG-243"]
    TCP_31773["TCP 31773"]
    TCP_9200["TCP 9200"]
    TCP_9100["TCP 9100"]
    TCP_9042_/_9160["TCP 9042 / 9160"]
    Node_mps1uX8T5PpobUmjtMyG_254["Node_mps1uX8T5PpobUmjtMyG-254"]
    AssetHost["AssetHost"]
    MinIO["MinIO"]
    ElasticSearch["ElasticSearch"]
    Cassandra["Cassandra"]
    Load_Balancer_/_Reverse_Proxy["Load Balancer / Reverse Proxy"]
    Node_mps1uX8T5PpobUmjtMyG_264["Node_mps1uX8T5PpobUmjtMyG-264"]
    WIRE["WIRE"]
    Server_2["Server 2"]
    Node_mps1uX8T5PpobUmjtMyG_267["Node_mps1uX8T5PpobUmjtMyG-267"]
    Node_mps1uX8T5PpobUmjtMyG_268["Node_mps1uX8T5PpobUmjtMyG-268"]
    Node_mps1uX8T5PpobUmjtMyG_271["Node_mps1uX8T5PpobUmjtMyG-271"]
    Kubernetes["Kubernetes"]
    Node_mps1uX8T5PpobUmjtMyG_273["Node_mps1uX8T5PpobUmjtMyG-273"]
    Node_mps1uX8T5PpobUmjtMyG_274["Node_mps1uX8T5PpobUmjtMyG-274"]
    Node_mps1uX8T5PpobUmjtMyG_279["Node_mps1uX8T5PpobUmjtMyG-279"]
    Node_mps1uX8T5PpobUmjtMyG_280["Node_mps1uX8T5PpobUmjtMyG-280"]
    Node_mps1uX8T5PpobUmjtMyG_285["Node_mps1uX8T5PpobUmjtMyG-285"]
    Node_mps1uX8T5PpobUmjtMyG_286["Node_mps1uX8T5PpobUmjtMyG-286"]
    Node_mps1uX8T5PpobUmjtMyG_297["Node_mps1uX8T5PpobUmjtMyG-297"]
    Node_mps1uX8T5PpobUmjtMyG_308["Node_mps1uX8T5PpobUmjtMyG-308"]
    MinIO["MinIO"]
    ElasticSearch["ElasticSearch"]
    Cassandra["Cassandra"]
    WIRE["WIRE"]
    Load_Balancer_/_Reverse_Proxy["Load Balancer / Reverse Proxy"]
    Node_mps1uX8T5PpobUmjtMyG_318["Node_mps1uX8T5PpobUmjtMyG-318"]
    WIRE["WIRE"]
    Server_3(same_topology)["Server 3(same topology)"]
    End_Users["End Users"]
    End_Users["End Users"]
    End_Users["End Users"]
    Internal_Network["Internal Network"]
    Internet["Internet"]
    Server_Topology_Legend["Server Topology Legend"]
    Wire_Network_Topology_Diagram["Wire Network Topology Diagram"]
    Node_mps1uX8T5PpobUmjtMyG_337["Node_mps1uX8T5PpobUmjtMyG-337"]
    Node_mps1uX8T5PpobUmjtMyG_339["Node_mps1uX8T5PpobUmjtMyG-339"]
    Node_mps1uX8T5PpobUmjtMyG_340["Node_mps1uX8T5PpobUmjtMyG-340"]
    Node_mps1uX8T5PpobUmjtMyG_345["Node_mps1uX8T5PpobUmjtMyG-345"]
    Node_mps1uX8T5PpobUmjtMyG_346["Node_mps1uX8T5PpobUmjtMyG-346"]
    WIRE["WIRE"]
    Internet["Internet"]
    WIRE["WIRE"]
    Proxy["Proxy"]
    TCP_9100["TCP 9100"]
    TCP_7000["TCP 7000"]
    TCP_9200["TCP 9200"]
    TCP_9200["TCP 9200"]
    TCP_9200["TCP 9200"]
    Node_mps1uX8T5PpobUmjtMyG_366["Node_mps1uX8T5PpobUmjtMyG-366"]
    Node_mps1uX8T5PpobUmjtMyG_367["Node_mps1uX8T5PpobUmjtMyG-367"]
    AdminandAssetHosts["AdminandAssetHosts"]
    =_client_connection_via_internet_(www),_TCP_Port_443_traffic["= client connection via internet (www), TCP Port 443 traffic"]
    =_client_connection_via_internet_(www),_UDP_(voice/video_calling),Ports_32768___61000_(as_specificied_in_/proc/sys/net/ipv4/ip_local_port_range),_adjustable_based_on_customer_requirements["= client connection via internet (www), UDP (voice/video calling),Ports 32768 - 61000 (as specificied in /proc/sys/net/ipv4/ip_local_port_range), adjustable based on customer requirements"]
    =_client_connection_via_internal_network_or_VPN_connection,_TCP_Port_443_traffic["= client connection via internal network or VPN connection, TCP Port 443 traffic"]
    =_client_connection_via_internal_network_or_VPN_connection,_UDP_(voice/video_calling),        _Ports_32768_61000_(as_specificied_in_/proc/sys/net/ipv4/ip_local_port_range),_adjustable_based_on_customer_requirements["= client connection via internal network or VPN connection, UDP (voice/video calling),         Ports 32768-61000 (as specificied in /proc/sys/net/ipv4/ip_local_port_range), adjustable based on customer requirements"]
    Admin_Host_communicates_with_all_Wire_backend_components_via_port_22Asset_Host___all_Wire_backend_components_communicate_with_the_Asset_Host_via_port_80 and_port_8080["Admin Host communicates with all Wire backend components via port 22Asset Host - all Wire backend components communicate with the Asset Host via port 80 and port 8080"]
    Node_mps1uX8T5PpobUmjtMyG_408["Node_mps1uX8T5PpobUmjtMyG-408"]
    Node_mps1uX8T5PpobUmjtMyG_409["Node_mps1uX8T5PpobUmjtMyG-409"]
    Node_mps1uX8T5PpobUmjtMyG_410["Node_mps1uX8T5PpobUmjtMyG-410"]
    Node_mps1uX8T5PpobUmjtMyG_413["Node_mps1uX8T5PpobUmjtMyG-413"]
    Kubernetes["Kubernetes"]
    Node_mps1uX8T5PpobUmjtMyG_460["Node_mps1uX8T5PpobUmjtMyG-460"]
    SFT["SFT"]
    DMZ["DMZ"]
    80,_1024_65535["80, 1024-65535"]
    Node_mps1uX8T5PpobUmjtMyG_112["Node_mps1uX8T5PpobUmjtMyG-112"]
    RESTUND["RESTUND"]
    Node_mps1uX8T5PpobUmjtMyG_471["Node_mps1uX8T5PpobUmjtMyG-471"]
    Node_mps1uX8T5PpobUmjtMyG_472["Node_mps1uX8T5PpobUmjtMyG-472"]
    Node_mps1uX8T5PpobUmjtMyG_473["Node_mps1uX8T5PpobUmjtMyG-473"]
    Node_mps1uX8T5PpobUmjtMyG_476["Node_mps1uX8T5PpobUmjtMyG-476"]
    Kubernetes["Kubernetes"]
    Node_mps1uX8T5PpobUmjtMyG_478["Node_mps1uX8T5PpobUmjtMyG-478"]
    SFT["SFT"]
    DMZ["DMZ"]
    80,_1024_65535["80, 1024-65535"]
    Node_mps1uX8T5PpobUmjtMyG_492["Node_mps1uX8T5PpobUmjtMyG-492"]
    RESTUND["RESTUND"]
    Node_mps1uX8T5PpobUmjtMyG_498["Node_mps1uX8T5PpobUmjtMyG-498"]
    Node_mps1uX8T5PpobUmjtMyG_499["Node_mps1uX8T5PpobUmjtMyG-499"]
    Node_mps1uX8T5PpobUmjtMyG_500["Node_mps1uX8T5PpobUmjtMyG-500"]
    Node_mps1uX8T5PpobUmjtMyG_503["Node_mps1uX8T5PpobUmjtMyG-503"]
    Kubernetes["Kubernetes"]
    Node_mps1uX8T5PpobUmjtMyG_505["Node_mps1uX8T5PpobUmjtMyG-505"]
    SFT["SFT"]
    DMZ["DMZ"]
    WIRE["WIRE"]
    TCP_6443TCP_2379___2380TCP_10250/10251/10252/10255TCP_3000_32767TCP_6379["TCP 6443TCP 2379 - 2380TCP 10250/10251/10252/10255TCP 3000-32767TCP 6379"]
    WIRE["WIRE"]
    WIRE["WIRE"]
    80,_1024_65535["80, 1024-65535"]
    Node_mps1uX8T5PpobUmjtMyG_541["Node_mps1uX8T5PpobUmjtMyG-541"]
    Node_mps1uX8T5PpobUmjtMyG_542["Node_mps1uX8T5PpobUmjtMyG-542"]
    Node_mps1uX8T5PpobUmjtMyG_39 --> Node_mps1uX8T5PpobUmjtMyG_214
    Node_mps1uX8T5PpobUmjtMyG_39 --> Node_mps1uX8T5PpobUmjtMyG_106
    Node_mps1uX8T5PpobUmjtMyG_39 --> Node_mps1uX8T5PpobUmjtMyG_99
    Node_mps1uX8T5PpobUmjtMyG_214 --> Node_mps1uX8T5PpobUmjtMyG_226
    Node_mps1uX8T5PpobUmjtMyG_179 --> Node_mps1uX8T5PpobUmjtMyG_183
    Node_mps1uX8T5PpobUmjtMyG_232 --> Node_mps1uX8T5PpobUmjtMyG_99
    Node_mps1uX8T5PpobUmjtMyG_220 --> Node_mps1uX8T5PpobUmjtMyG_93
    Node_mps1uX8T5PpobUmjtMyG_226 --> Node_mps1uX8T5PpobUmjtMyG_106
    Node_mps1uX8T5PpobUmjtMyG_226 --> Node_mps1uX8T5PpobUmjtMyG_39
    Node_mps1uX8T5PpobUmjtMyG_106 --> Node_mps1uX8T5PpobUmjtMyG_214
    Node_mps1uX8T5PpobUmjtMyG_366 --> Node_mps1uX8T5PpobUmjtMyG_366
    Node_mps1uX8T5PpobUmjtMyG_366 --> Node_mps1uX8T5PpobUmjtMyG_366
    Node_mps1uX8T5PpobUmjtMyG_366 --> Node_mps1uX8T5PpobUmjtMyG_366
    Node_mps1uX8T5PpobUmjtMyG_366 --> Node_mps1uX8T5PpobUmjtMyG_366
    Node_mps1uX8T5PpobUmjtMyG_410 --> Node_mps1uX8T5PpobUmjtMyG_112
    Node_mps1uX8T5PpobUmjtMyG_473 --> Node_mps1uX8T5PpobUmjtMyG_492
    Node_mps1uX8T5PpobUmjtMyG_410 --> Node_mps1uX8T5PpobUmjtMyG_473
    Node_mps1uX8T5PpobUmjtMyG_337 --> SFT
    Node_mps1uX8T5PpobUmjtMyG_339 --> SFT
    Node_mps1uX8T5PpobUmjtMyG_337 --> SFT
    Node_mps1uX8T5PpobUmjtMyG_337 --> Node_mps1uX8T5PpobUmjtMyG_112
    Node_mps1uX8T5PpobUmjtMyG_337 --> Node_mps1uX8T5PpobUmjtMyG_492
    Node_mps1uX8T5PpobUmjtMyG_340 --> SFT
    Node_mps1uX8T5PpobUmjtMyG_340 --> Node_mps1uX8T5PpobUmjtMyG_492
    Node_mps1uX8T5PpobUmjtMyG_112 --> Node_mps1uX8T5PpobUmjtMyG_492