name: Build Test

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'Release.md'
      - '.github/**'
      - 'build/**'
      - Makefile

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: cachix/install-nix-action@v16

      - name: Build Docs
        id: build_docs
        run: |
          make build
