name: CI Build

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/workflows/release.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: cachix/install-nix-action@v16

      - name: Run make build
        run: make build
