name: Prod Env Latest Build

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'Release.md'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: cachix/install-nix-action@v16

      - name: Build Archive
        id: build_archive
        run: |
          make archive
          if [ ! -f "wire-docs.tar.gz" ]; then
            echo "Artifact not found!"
            exit 1
          fi
